# Generated by Django 4.0.6 on 2022-07-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('COOKING', 'Cooking'), ('READY', 'Ready'), ('ONTHEWAY', 'On the way'), ('DELIVERED', 'Delivered')], default='COOKING', max_length=50),
        ),
    ]
