# Generated by Django 4.0.6 on 2022-07-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_menuitem_image_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
