# Generated by Django 4.0.6 on 2022-07-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[(59, 'Kenitra'), (1, 'Rabat')], default='Kenitra', max_length=50),
        ),
    ]
